version: "2"

services:

  dev-deploy:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "AWS_ACCESS_KEY_ID=${DEV_DEPLOY_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${DEV_DEPLOY_AWS_SECRET_ACCESS_KEY}"
      - "DYNAMO_TABLE=${DEV_DYNAMO_TABLE}"
      - "KEBOOLA_STACK=${DEV_KEBOOLA_STACK}"
      - "PAPERTRAIL_PORT=${DEV_PAPERTRAIL_PORT}"
      - "REGION=${DEV_REGION}"
      - "S3_BUCKET=${DEV_S3_BUCKET}"
      - "SERVICE_NAME=${DEV_SERVICE_NAME}"
      - "STAGE=dev"
    command: >
             sh -c '
             serverless deploy
             '
  ci-deploy:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "AWS_ACCESS_KEY_ID=${CI_DEPLOY_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${CI_DEPLOY_AWS_SECRET_ACCESS_KEY}"
      - "DYNAMO_TABLE=${CI_DYNAMO_TABLE}"
      - "KEBOOLA_STACK=${CI_KEBOOLA_STACK}"
      - "PAPERTRAIL_PORT=${CI_PAPERTRAIL_PORT}"
      - "REGION=${CI_REGION}"
      - "S3_BUCKET=${CI_S3_BUCKET}"
      - "SERVICE_NAME=${CI_SERVICE_NAME}"
      - "STAGE=test"
    command: >
             sh -c '
             serverless deploy
             '

  prod-deploy-us:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "AWS_ACCESS_KEY_ID=${PROD_DEPLOY_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${PROD_DEPLOY_AWS_SECRET_ACCESS_KEY}"
      - "DYNAMO_TABLE=${PROD_DYNAMO_TABLE}"
      - "KEBOOLA_STACK=${PROD_KEBOOLA_STACK}"
      - "PAPERTRAIL_PORT=${PROD_PAPERTRAIL_PORT}"
      - "REGION=${PROD_REGION}"
      - "S3_BUCKET=${PROD_S3_BUCKET}"
      - "SERVICE_NAME=${PROD_SERVICE_NAME}"
      - "STAGE=prod"
    command: >
             sh -c '
             serverless deploy
             '

  prod-deploy-eu:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "AWS_ACCESS_KEY_ID=${PROD_DEPLOY_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${PROD_DEPLOY_AWS_SECRET_ACCESS_KEY}"
      - "DYNAMO_TABLE=${PROD_EU_DYNAMO_TABLE}"
      - "KEBOOLA_STACK=${PROD_KEBOOLA_STACK}"
      - "PAPERTRAIL_PORT=${PROD_PAPERTRAIL_PORT}"
      - "REGION=${PROD_EU_REGION}"
      - "S3_BUCKET=${PROD_EU_S3_BUCKET}"
      - "SERVICE_NAME=${PROD_EU_SERVICE_NAME}"
      - "STAGE=prod"
    command: >
             sh -c '
             serverless deploy
             '

  dev-test-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    links:
      - localstack
    environment:
      - "AWS_ACCESS_KEY_ID=accessKey"
      - "AWS_SECRET_ACCESS_KEY=secretKey"
      - "DYNAMO_ENDPOINT=http://localstack:4569"
      - "DYNAMO_TABLE=emails"
      - "REGION=us-east-1"
      - "S3_BUCKET=emails"
      - "S3_ENDPOINT=http://localstack:4572"
    command: >
             sh -c '
             ./node_modules/.bin/mocha --timeout 0 test/handler.js
             '

  dev-test-func:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    working_dir: /code
    environment:
      - "AWS_ACCESS_KEY_ID=${DEV_TEST_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${DEV_TEST_AWS_SECRET_ACCESS_KEY}"
      - "DYNAMO_TABLE=${DEV_DYNAMO_TABLE}"
      - "KEBOOLA_STACK=${DEV_KEBOOLA_STACK}"
      - "PAPERTRAIL_PORT=${DEV_PAPERTRAIL_PORT}"
      - "REGION=${DEV_REGION}"
      - "S3_BUCKET=${DEV_S3_BUCKET}"
      - "SERVICE_NAME=${DEV_SERVICE_NAME}"
      - "STAGE=dev"
    command: >
             sh -c '
             ./node_modules/.bin/mocha --timeout 0 test/func.js
             '

  ci-test-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - localstack
    environment:
      - "AWS_ACCESS_KEY_ID=accessKey"
      - "AWS_SECRET_ACCESS_KEY=secretKey"
      - "DYNAMO_ENDPOINT=http://localstack:4569"
      - "DYNAMO_TABLE=emails"
      - "REGION=us-east-1"
      - "S3_BUCKET=emails"
      - "S3_ENDPOINT=http://localstack:4572"
    command: >
             sh -c '
             ./node_modules/.bin/mocha --timeout 0 test/handler.js
             '

  ci-test-func:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "AWS_ACCESS_KEY_ID=${CI_TEST_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${CI_TEST_AWS_SECRET_ACCESS_KEY}"
      - "DYNAMO_TABLE=${CI_DYNAMO_TABLE}"
      - "KEBOOLA_STACK=${CI_KEBOOLA_STACK}"
      - "PAPERTRAIL_PORT=${CI_PAPERTRAIL_PORT}"
      - "REGION=${CI_REGION}"
      - "S3_BUCKET=${CI_S3_BUCKET}"
      - "SERVICE_NAME=${CI_SERVICE_NAME}"
      - "STAGE=test"
    command: >
             sh -c '
             ./node_modules/.bin/mocha --timeout 0 test/func.js
             '

  localstack:
    image: localstack/localstack
    ports:
      - "4569:4569"
      - "4572:4572"
    environment:
      - "SERVICES=s3,dynamodb"
