version: "2"

services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: keboola/ex-email-attachments-lambda
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      CLOUDFORMATION_ROLE_ARN:
      LAMBDA_EXECUTION_ROLE_ARN:
      DYNAMO_TABLE:
      EMAIL_DOMAIN:
      KEBOOLA_STACK:
      REGION:
      S3_BUCKET:
      SERVICE_NAME:
      STAGE:

  dev:
    <<: *app
    volumes:
      - .:/code

  test-app:
    <<: *app
    links:
      - localstack
    environment:
      AWS_ACCESS_KEY_ID: accessKey
      AWS_SECRET_ACCESS_KEY: secretKey
      DYNAMO_ENDPOINT: http://localstack:4566
      DYNAMO_TABLE: emails
      EMAIL_DOMAIN: import.test.keboola.com
      REGION: us-east-1
      S3_BUCKET: emails
      S3_ENDPOINT: http://localstack:4566
    command: yarn test-unit

  test-func:
    <<: *app
    command: yarn test-func

  deploy:
    <<: *app
    command: sh -c 'serverless deploy && serverless s3deploy'

  localstack:
    image: localstack/localstack:1.4.0
    ports:
      - "4566:4566"
    environment:
      - "SERVICES=s3,dynamodb"
