name: Build & Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDFORMATION_ROLE_ARN: arn:aws:iam::061240556736:role/ci-ex-email-attachments-us-east-1-sls-cf
      LAMBDA_EXECUTION_ROLE_ARN: arn:aws:iam::061240556736:role/ci-ex-email-attachments-us-east-1-sls-exec
      DYNAMO_TABLE: ci-ex-email-attachments-us-east-1-emails
      EMAIL_DOMAIN: import.testing.keboola.com
      KEBOOLA_STACK: ex-email-attachments
      REGION: us-east-1
      S3_BUCKET: ci-ex-email-attachments-us-east-1-emails
      SERVICE_NAME: ci-ex-email-attachments
      STAGE: test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: keboola/ex-email-attachments-lambda
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run unit tests
        run: docker-compose run --rm test-app

      - name: Deploy to CI testing
        run: docker-compose run --rm deploy
        env:
          AWS_ACCESS_KEY_ID: AKIAQ4QRYXTAAU3SUAVH
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_DEPLOY_AWS_SECRET_ACCESS_KEY }}

      - name: Run functional tests
        run: docker-compose run --rm test-func
        env:
          AWS_ACCESS_KEY_ID: AKIAQ4QRYXTAOOVQLNW6
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_TEST_AWS_SECRET_ACCESS_KEY }}

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: AKIASE4SHFLW2SABQJOP
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_DEPLOY_AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: keboola/ex-email-attachments-lambda
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to production (US)
        run: docker-compose run --rm deploy
        env:
          CLOUDFORMATION_ROLE_ARN: arn:aws:iam::147946154733:role/ex-email-attachments-us-east-1-sls-cf
          LAMBDA_EXECUTION_ROLE_ARN: arn:aws:iam::147946154733:role/ex-email-attachments-us-east-1-sls-exec
          DYNAMO_TABLE: ex-email-attachments-us-east-1-emails
          EMAIL_DOMAIN: import.keboola.com
          KEBOOLA_STACK: ex-email-attachments
          REGION: us-east-1
          S3_BUCKET: ex-email-attachments-us-east-1-emails
          SERVICE_NAME: ex-email-attachments
          STAGE: prod

      - name: Deploy to production (EU)
        run: docker-compose run --rm deploy
        env:
          CLOUDFORMATION_ROLE_ARN: arn:aws:iam::147946154733:role/ex-email-attachments-eu-central-1-sls-cf
          LAMBDA_EXECUTION_ROLE_ARN: arn:aws:iam::147946154733:role/ex-email-attachments-eu-central-1-sls-exec
          DYNAMO_TABLE: ex-email-attachments-eu-central-1-emails
          EMAIL_DOMAIN: import.eu-central-1.keboola.com
          KEBOOLA_STACK: ex-email-attachments
          REGION: eu-central-1
          S3_BUCKET: ex-email-attachments-eu-central-1-emails
          SERVICE_NAME: ex-email-attachments
          STAGE: prod
