name: Build
on: [push]

env:
  CLOUDFORMATION_ROLE_ARN: arn:aws:iam::061240556736:role/ci-ex-email-attachments-us-east-1-sls-cf
  LAMBDA_EXECUTION_ROLE_ARN: arn:aws:iam::061240556736:role/ci-ex-email-attachments-us-east-1-sls-exec
  DYNAMO_TABLE: ci-ex-email-attachments-us-east-1-emails
  EMAIL_DOMAIN: import.testing.keboola.com
  KEBOOLA_STACK: ex-email-attachments
  REGION: us-east-1
  S3_BUCKET: ci-ex-email-attachments-us-east-1-emails
  SERVICE_NAME: ci-ex-email-attachments
  STAGE: test

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build

      - name: Run unit tests
        run: docker-compose run --rm test-app

      - name: Deploy to CI testing
        run: docker-compose run --rm deploy
        env:
          AWS_ACCESS_KEY_ID: AKIAQ4QRYXTAAU3SUAVH
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_DEPLOY_AWS_SECRET_ACCESS_KEY }}

      - name: Run functional tests
        run: docker-compose run --rm test-func
        env:
          AWS_ACCESS_KEY_ID: AKIAQ4QRYXTAOOVQLNW6
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_TEST_AWS_SECRET_ACCESS_KEY }}
