name: Deploy
on:
  workflow_run:
    workflows: [Build]
    branches: [master]
    types: [completed]

env:
  AWS_ACCESS_KEY_ID: AKIAIMEIMENLMSSY4EBQ
  AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_DEPLOY_AWS_SECRET_ACCESS_KEY }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production (US)
        run: |
          echo "Deployed"
          env
#        run: docker-compose run --rm deploy
        env:
          CLOUDFORMATION_ROLE_ARN: arn:aws:iam::147946154733:role/ex-email-attachments-us-east-1-sls-cf
          LAMBDA_EXECUTION_ROLE_ARN: arn:aws:iam::147946154733:role/ex-email-attachments-us-east-1-sls-exec
          DYNAMO_TABLE: ex-email-attachments-us-east-1-emails
          EMAIL_DOMAIN: import.keboola.com
          KEBOOLA_STACK: ex-email-attachments
          REGION: us-east-1
          S3_BUCKET: ex-email-attachments-us-east-1-emails
          SERVICE_NAME: ex-email-attachments
          STAGE: prod

      - name: Deploy to production (EU)
        run: |
          echo "Deployed"
          env
#        run: docker-compose run --rm deploy
        env:
          CLOUDFORMATION_ROLE_ARN: arn:aws:iam::147946154733:role/ex-email-attachments-eu-central-1-sls-cf
          LAMBDA_EXECUTION_ROLE_ARN: arn:aws:iam::147946154733:role/ex-email-attachments-eu-central-1-sls-exec
          DYNAMO_TABLE: ex-email-attachments-eu-central-1-emails
          EMAIL_DOMAIN: import.eu-central-1.keboola.com
          KEBOOLA_STACK: ex-email-attachments
          REGION: eu-central-1
          S3_BUCKET: ex-email-attachments-eu-central-1-emails
          SERVICE_NAME: ex-email-attachments
          STAGE: prod
